### PR TITLE
Implement check for max title length

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by WoutResseler** [comment]
@bastelfreak Is there any specific reason why you made the max title length 26 chars? I ran into this limit today and was wondering what the reasoning behind this limit is :)

**Comment by bastelfreak** [comment]
I think there is a limit of 32 chars within ipsets. during an update, the script creates a temporary chain with the original name + somthing like `-temp` which hits the 32 chars limit.

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/puppet-ipset/blob/master/files/ipset_sync#L225 I think that's the prefix we prepend to the original set name.

**Comment by WoutResseler** [comment]
Ah I see, that makes sense! Thanks for the quick response :)

**Pull request merged**
