### PR TITLE
Adding dependency on debian iptables service.

### PR DESCRIPTION
**Pull request by oliparcol**
#### Pull Request (PR) description

This PR adds a *Before* declaration on `netfilter-persistent.service` which is the service in Debian and Ubuntu that restores the iptables rules.

#### This Pull Request (PR) fixes the following issues

This PR prevents `netfilter-persistent.service` from failing on non-existent ipset.

### CODE REVIEW

**Comment by oliparcol** [comment]
Please note that the CI is failing on code already in `master`.

**Comment by bastelfreak** [comment]
@oliparcol thanks for the PR. can you please rebase against master?

**Comment by oliparcol** [comment]
done, sorry for the delay

**Review by kenyon — COMMENTED** [review]
What if netfilter-persistent is not installed?

**Comment by oliparcol** [comment]
> What if netfilter-persistent is not installed?

It works (ubuntu/debian has the same issue with `iptables.service ip6tables.service` that don't exist) but I agree, it's not very clean. How about I refactor the PR to pass the firewall services to `firewall_service` and I initialize this variable with either `iptables.service ip6tables.service` or `netfilter-persistent.service` depending on OS family ?

**Review by kenyon — APPROVED** [review]
Ah OK, I just tested it, systemd doesn't care if a unit listed in `Before=` doesn't exist, it doesn't give an error or warning. So this seems fine as is.

**Pull request merged**
