### PR TITLE
this is a fix for newer kernel and resolves #68

### LINKED ISSUE #68: The module doesn't work if ipset in use
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.14
- Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
- Distribution: Ubuntu 22.04 LTS
- Module version: 1.2.3 (I see this bug in code 2.1.0) 

## How to reproduce (e.g Puppet code you use)
Create ipset and add iptables rule for use this ipset
Example:
`iptables -A INPUT -m set --match-set test src -j ACCEPT`

## What are you seeing
We found that when using the ipset firewall or ubuntu 20 and older, the address addition does not occur.
The error occurs while running the ipset_sync script

## Output log
ipset v7.15: Set cannot be destroyed: it is in use by a kernel component
ipset v7.15: Error in line 1: Set cannot be created: set with the same name already exists

## Any additional information you'd like to impart
We create new function in ipset_sync
```bash
function import_ipset_new() {
  local id=$1
  local alias=${2:-${id}}
  local no_content=${3:-0}
  local f_content=$(get_content_file ${id})
  if [ ! -f "${f_content}" ]; then
    echo "Set configuration file '${f_content}' does not exist!" >&2
    exit 6
  else
    while read LINE; do
            ipset add ${id} $LINE
    done < ${f_content}
  fi

}
```

and change lines 
`ipset destroy ${set_id}` to `ipset flush ${set_id}`
`import_ipset ${set_id} ${set_id} ${ignore_contents}` to
`import_ipset_new ${set_id} ${set_id} ${ignore_contents}`

### PR DESCRIPTION
**Pull request by muncjack**
#### Pull Request (PR) description
This is for resolving a problem with ipset on ubuntu 22.04 LTS 
The new version of ipset add extra header messages  

#### This Pull Request (PR) fixes the following issues
Fixes #68

### CODE REVIEW

**Comment by bastelfreak** [comment]
Can you place add Ubuntu 22.04 to metadata.json?

**Comment by muncjack** [comment]
I have added ubuntu to the metadata.json file :-)

**Comment by maxadamo** [comment]
@bastelfreak sorry for messing up with the labels.
Now Ubuntu 22.04 was added, and it looks good to me.

**Review by maxadamo — APPROVED** [review]
the `sed` commands were moved inside the function, and they are the same as in #67 , but the pre-prending space is also removed (which was necessary)

**Review by bastelfreak — APPROVED** [review]

**Comment by maxadamo** [comment]
supersedes #67

**Pull request merged**
